# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_RTrollBase_rcpp_hello_world`)
}

readl <- function(path, lines) {
    .Call(`_RTrollBase_readl`, path, lines)
}

str_split_cpp <- function(s) {
    .Call(`_RTrollBase_str_split_cpp`, s)
}

recup_troll_str_vec <- function(filename) {
    .Call(`_RTrollBase_recup_troll_str_vec`, filename)
}

