# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert a date in format AAAAQQ in standard date format
#'
#' @param datestring a string containing the date in AAAAQQ format
#' @return A Date object
Qdate <- function(datestring) {
    .Call(`_RTrollBase_Qdate`, datestring)
}

#' Convert a date vector in format AAAAQQ in standard date format
#'
#' @param datevect a vector of strings containing the dates in AAAAQQ format
#' @return A DateVector object
Qdatevect <- function(datevect) {
    .Call(`_RTrollBase_Qdatevect`, datevect)
}

#' Add a quarter to a date (in format YYYY-MM-01 with MM in {01, 04, 07, 10})
#'
#' @param currentdate A date for the begining of a quarter
#' @return A Date object
AddQuarter <- function(currentdate) {
    .Call(`_RTrollBase_AddQuarter`, currentdate)
}

#' Add a quarter to a date (in format AAAAQQ)
#'
#' @param datestring A date (string)
#' @return A string containing the new date
AddQuarterStr <- function(datestring) {
    .Call(`_RTrollBase_AddQuarterStr`, datestring)
}

#' function to split at spaces or eol (internal)
#'
#' @param s A string containing the whole file
#' @return A vector of strings 
str_split_cpp <- function(s) {
    .Call(`_RTrollBase_str_split_cpp`, s)
}

#' Read a Troll database in text format
#' The file is split by space character
#'
#' @param filename A string containing the name of the file
#' @return A vector of strings 
recup_troll_str_vec <- function(filename) {
    .Call(`_RTrollBase_recup_troll_str_vec`, filename)
}

#' Read a Troll database in text format
#' The file is split by space character
#'
#' @param str_vec A vector of strings containing the data
#' @return A List
recup_troll <- function(str_vec) {
    .Call(`_RTrollBase_recup_troll`, str_vec)
}

#' Merge two dataframes based on the date column 
#'
#' @param left a data.frame with a date column
#' @param right a data.frame with a date column
#' @return A data.frame
dateMerge <- function(left, right) {
    .Call(`_RTrollBase_dateMerge`, left, right)
}

