# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

str_split_cpp <- function(s) {
    .Call(`_RTrollBase_str_split_cpp`, s)
}

recup_troll_str_vec <- function(filename) {
    .Call(`_RTrollBase_recup_troll_str_vec`, filename)
}

recup_troll <- function(str_vec) {
    .Call(`_RTrollBase_recup_troll`, str_vec)
}

